from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from datetime import datetime
from pydantic import BaseModel
from typing import List, Optional
import io
import os

# PDF generation
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.enums import TA_CENTER, TA_LEFT

# OpenAI
from openai import OpenAI

app = FastAPI(title="Axulo PMaaS API", version="1.0.0")

# CORS for frontend
app.add_middleware(
    CORSMiddleware,
    allow_origins=["http://localhost:3000"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Initialize OpenAI client (will be None if no API key)
openai_client = OpenAI(api_key=os.getenv("OPENAI_API_KEY")) if os.getenv("OPENAI_API_KEY") else None

# ========== REQUEST MODELS ==========
class ProjectIntake(BaseModel):
    company_name: str
    industry: str
    country: str
    employees: int
    project_name: str
    business_problem: str
    desired_outcome: str
    strategic_objectives: List[str]
    budget: float
    timeline: str
    assumptions: List[str] = []
    constraints: List[str] = []
    risks: List[str] = []

class CharterRequest(BaseModel):
    intake: ProjectIntake
    additional_context: Optional[str] = None

# ========== BASIC ENDPOINTS ==========
@app.get("/")
def root():
    return {"message": "Axulo PMaaS API", "status": "operational"}

@app.get("/health")
def health_check():
    return {"status": "healthy", "timestamp": datetime.now().isoformat()}

@app.get("/api/test")
def test():
    return {"message": "API is working! Welcome to Axulo PMaaS"}

# ========== BASIC CHARTER GENERATION ==========
@app.post("/api/generate-charter")
async def generate_charter(request: CharterRequest):
    """Generate a professional project charter (template-based)"""
    
    formatted_budget = f"${request.intake.budget:,.2f}"
    
    objectives_text = "\n".join(f"- {obj}" for obj in request.intake.strategic_objectives)
    risks_text = "\n".join(f"- {risk}" for risk in request.intake.risks)
    
    charter = f"""
# PROJECT CHARTER
## {request.intake.project_name}

### Executive Summary
{request.intake.company_name} is undertaking the {request.intake.project_name} project to address: {request.intake.business_problem}

### Business Case
The project will deliver: {request.intake.desired_outcome}
With a budget of {formatted_budget} over {request.intake.timeline}.

### Strategic Objectives
{objectives_text}

### Key Stakeholders
- Project Sponsor: {request.intake.company_name} Leadership
- Project Manager: Axulo PMaaS
- Affected Departments: Operations, Technology, Management

### Success Criteria
- Project completed within {formatted_budget} budget
- Timeline met: {request.intake.timeline}
- Business problem resolved: {request.intake.business_problem}
- Desired outcome achieved: {request.intake.desired_outcome}

### High-Level Risks
{risks_text}

### Approval
This charter authorizes the project to proceed.

---
*Generated by Axulo PMaaS - AI-Powered Project Management*
"""
    
    return {
        "project_name": request.intake.project_name,
        "charter": charter,
        "generated_at": datetime.now().isoformat()
    }

# ========== AI-POWERED CHARTER GENERATION ==========
@app.post("/api/generate-ai-charter")
async def generate_ai_charter(request: CharterRequest):
    """Generate an AI-powered professional project charter using OpenAI"""
    
    if not openai_client:
        return {
            "error": "OpenAI API key not configured",
            "message": "Please set OPENAI_API_KEY environment variable",
            "charter": "OpenAI API key not configured. Please add your API key to use AI-powered generation."
        }
    
    formatted_budget = f"${request.intake.budget:,.2f}"
    
    prompt = f"""
You are a senior PMP-certified Project Director with 20+ years of experience. Create a professional, executive-level project charter.

PROJECT INFORMATION:
- Company: {request.intake.company_name} (Industry: {request.intake.industry}, Country: {request.intake.country}, Employees: {request.intake.employees})
- Project Name: {request.intake.project_name}
- Business Problem: {request.intake.business_problem}
- Desired Outcome: {request.intake.desired_outcome}
- Strategic Objectives: {', '.join(request.intake.strategic_objectives)}
- Budget: {formatted_budget}
- Timeline: {request.intake.timeline}
- Initial Risks: {', '.join(request.intake.risks)}

Generate a complete project charter with these sections:
1. **Executive Summary** - Compelling overview
2. **Business Case** - ROI, strategic alignment, key benefits
3. **Scope Statement** - In Scope / Out of Scope
4. **Key Deliverables** with success criteria
5. **Stakeholder Register** - Categorize by influence/interest
6. **High-level Timeline** with milestones
7. **Budget Summary** with allocation recommendations
8. **Risk Register** (Probability 1-5, Impact 1-5, Mitigation strategies)
9. **Assumptions and Constraints**
10. **Approval Section**

Format with professional markdown. Be specific, actionable, and executive-ready.
"""
    
    try:
        response = openai_client.chat.completions.create(
            model="gpt-4o-mini",
            messages=[
                {"role": "system", "content": "You are an expert Project Management consultant. Produce executive-quality, actionable project charters."},
                {"role": "user", "content": prompt}
            ],
            temperature=0.7,
            max_tokens=2000
        )
        
        charter = response.choices[0].message.content
        
        return {
            "project_name": request.intake.project_name,
            "charter": charter,
            "generated_at": datetime.now().isoformat(),
            "ai_powered": True
        }
    except Exception as e:
        return {
            "error": str(e),
            "message": "OpenAI API error. Please check your API key.",
            "charter": f"Error generating AI charter: {str(e)}"
        }

# ========== PDF EXPORT ==========
@app.post("/api/export-pdf")
async def export_charter_to_pdf(request: CharterRequest):
    """Export project charter as PDF"""
    
    buffer = io.BytesIO()
    doc = SimpleDocTemplate(buffer, pagesize=letter)
    styles = getSampleStyleSheet()
    
    # Custom styles
    title_style = ParagraphStyle(
        'CustomTitle',
        parent=styles['Heading1'],
        fontSize=24,
        textColor='#1e40af',
        alignment=TA_CENTER,
        spaceAfter=30
    )
    
    heading_style = ParagraphStyle(
        'CustomHeading',
        parent=styles['Heading2'],
        fontSize=16,
        textColor='#1e40af',
        spaceAfter=12,
        spaceBefore=20
    )
    
    normal_style = ParagraphStyle(
        'CustomNormal',
        parent=styles['Normal'],
        fontSize=11,
        alignment=TA_LEFT,
        spaceAfter=8
    )
    
    story = []
    
    # Title
    story.append(Paragraph("PROJECT CHARTER", title_style))
    story.append(Paragraph(request.intake.project_name, heading_style))
    story.append(Spacer(1, 0.2*inch))
    
    # Executive Summary
    story.append(Paragraph("Executive Summary", heading_style))
    story.append(Paragraph(f"{request.intake.company_name} is undertaking the {request.intake.project_name} project to address: {request.intake.business_problem}", normal_style))
    story.append(Spacer(1, 0.1*inch))
    
    # Business Case
    story.append(Paragraph("Business Case", heading_style))
    story.append(Paragraph(f"The project will deliver: {request.intake.desired_outcome}", normal_style))
    story.append(Paragraph(f"With a budget of ${request.intake.budget:,.2f} over {request.intake.timeline}.", normal_style))
    story.append(Spacer(1, 0.1*inch))
    
    # Strategic Objectives
    story.append(Paragraph("Strategic Objectives", heading_style))
    for obj in request.intake.strategic_objectives:
        story.append(Paragraph(f"• {obj}", normal_style))
    story.append(Spacer(1, 0.1*inch))
    
    # Key Stakeholders
    story.append(Paragraph("Key Stakeholders", heading_style))
    story.append(Paragraph(f"• Project Sponsor: {request.intake.company_name} Leadership", normal_style))
    story.append(Paragraph("• Project Manager: Axulo PMaaS", normal_style))
    story.append(Spacer(1, 0.1*inch))
    
    # Success Criteria
    story.append(Paragraph("Success Criteria", heading_style))
    story.append(Paragraph(f"• Project completed within ${request.intake.budget:,.2f} budget", normal_style))
    story.append(Paragraph(f"• Timeline met: {request.intake.timeline}", normal_style))
    story.append(Paragraph(f"• Business problem resolved: {request.intake.business_problem}", normal_style))
    story.append(Paragraph(f"• Desired outcome achieved: {request.intake.desired_outcome}", normal_style))
    story.append(Spacer(1, 0.1*inch))
    
    # Risks
    story.append(Paragraph("High-Level Risks", heading_style))
    for risk in request.intake.risks:
        story.append(Paragraph(f"• {risk}", normal_style))
    
    doc.build(story)
    buffer.seek(0)
    
    return StreamingResponse(
        buffer,
        media_type="application/pdf",
        headers={"Content-Disposition": f"attachment; filename={request.intake.project_name}_charter.pdf"}
    )

